version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: spark-dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: spark
    ports:
      - "27017:27017"
    volumes:
      - ./script/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  redis:
    image: redis:alpine
    container_name: spark-dev-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password

  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "80:9000"