services:
  mongodb:
    image: mongo:latest
    container_name: spark-dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: spark
    ports:
      - 27017:27017
    volumes:
      - ./script/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: spark-dev-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@spark-dev-mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081

  redis:
    image: redis:alpine
    container_name: spark-dev-redis
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password